library(Seurat)
library(psupertime)

# ACM
seurat_object = Read10X("subset_mats_psupertime/ACM_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/ACM_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/ACM_psuper.Rds", compress=F)

# ARTE
seurat_object = Read10X("subset_mats_psupertime/ARTE_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/ARTE_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/ARTE_psuper.Rds", compress=F)

# CFIB
seurat_object = Read10X("subset_mats_psupertime/CFIB1_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/CFIB1_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/CFIB_psuper.Rds", compress=F)

# ENDO
seurat_object = Read10X("subset_mats_psupertime/ENDO_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/ENDO_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/ENDO_psuper.Rds", compress=F)

# EPI
seurat_object = Read10X("subset_mats_psupertime/EPI_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/EPI_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/EPI_psuper.Rds", compress=F)

# LYMPHE
seurat_object = Read10X("subset_mats_psupertime/LYMPHE_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/LYMPHE_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/LYMPHE_psuper.Rds", compress=F)

# MAC
seurat_object = Read10X("subset_mats_psupertime/MAC_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/MAC_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/MAC_psuper.Rds", compress=F)

# PERI
seurat_object = Read10X("subset_mats_psupertime/PERI_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/PERI_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/PERI_psuper.Rds", compress=F)

# SAN
seurat_object = Read10X("subset_mats_psupertime/SAN_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/SAN_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/SAN_psuper.Rds", compress=F)

# TCM
seurat_object = Read10X("subset_mats_psupertime/TCM_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/TCM_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/TCM_psuper.Rds", compress=F)

# VASCE
seurat_object = Read10X("subset_mats_psupertime/VASCE_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/VASCE_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/VASCE_psuper.Rds", compress=F)

# VCM
seurat_object = Read10X("subset_mats_psupertime/VCM_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/VCM_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/VCM_psuper.Rds", compress=F)

# VEC
seurat_object = Read10X("subset_mats_psupertime/VEC_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/VEC_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/VEC_psuper.Rds", compress=F)

# VIC
seurat_object = Read10X("subset_mats_psupertime/VIC_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/VIC_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/VIC_psuper.Rds", compress=F)

# VSM
seurat_object = Read10X("subset_mats_psupertime/VSM1_subset_mat")
seurat_object = CreateSeuratObject(seurat_object, names.field=c(1,2))
seurat_object[["percent_mito"]] <- PercentageFeatureSet(seurat_object, pattern = "^mt-")
meta = read.table("subset_meta_psupertime/VSM1_meta.txt", header=T)
seurat_object$Age = unlist(meta["Age"])
seurat_object$State = unlist(meta["State"])
seurat_object$Sex = unlist(meta["Sex"])
seurat_object = NormalizeData(seurat_object) 
seurat_object = FindVariableFeatures(seurat_object)
seurat_object = ScaleData(seurat_object)
sce_object = as.SingleCellExperiment(seurat_object)
timepoints = as.factor(seurat_object@meta.data$Age)
psuper_hvg = psupertime(sce_object, timepoints, sel_genes="all", penalization="best")
saveRDS(psuper_hvg, "subset_psupertime_res_allgenes/VSM_psuper.Rds", compress=F)
